package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"unicode"
)

const fileTemplate = `// Code generated by nina-generator; DO NOT EDIT.
package icons

import "github.com/fabregas/nina/nn"

func Icon(svgContent string) *nn.Element {
	return nn.Raw("svg", svgContent).
		Attr("xmlns", "http://www.w3.org/2000/svg").
		Attr("viewBox", "0 0 24 24").
		Attr("fill", "none").
		Attr("stroke", "currentColor").
		Attr("stroke-width", "2").
		Attr("stroke-linecap", "round").
		Attr("stroke-linejoin", "round").
		Class("shrink-0")
}

{{range .}}
// {{.FuncName}} returns content of {{.OriginalName}} icon
func {{.FuncName}}() *nn.Element {
	return Icon({{.FormattedSVG}})
}
{{end}}
`

type IconData struct {
	FuncName     string
	OriginalName string
	FormattedSVG string
}

func main() {
	svgDir := "../../lucide-svgs"
	outPath := "icons.go"

	files, err := os.ReadDir(svgDir)
	if err != nil {
		panic(err)
	}

	var icons []IconData

	for _, f := range files {
		if filepath.Ext(f.Name()) != ".svg" {
			continue
		}

		name := strings.TrimSuffix(f.Name(), ".svg")
		content, _ := os.ReadFile(filepath.Join(svgDir, f.Name()))
		svgStr := string(content)

		start := strings.Index(svgStr, ">") + 1
		end := strings.LastIndex(svgStr, "</svg>")
		if start <= 0 || end == -1 || start >= end {
			continue
		}

		inner := svgStr[start:end]

		inner = strings.ReplaceAll(inner, "\n", "")
		inner = strings.ReplaceAll(inner, "\t", " ")
		for strings.Contains(inner, "  ") {
			inner = strings.ReplaceAll(inner, "  ", " ")
		}
		inner = strings.TrimSpace(inner)

		inner = strings.ReplaceAll(inner, "`", "` + \"`\" + `")
		formattedSVG := "`" + inner + "`"

		icons = append(icons, IconData{
			FuncName:     toPascalCase(name),
			OriginalName: name,
			FormattedSVG: formattedSVG,
		})
	}

	tmpl := template.Must(template.New("icons").Parse(fileTemplate))
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, icons); err != nil {
		panic(err)
	}

	os.WriteFile(outPath, buf.Bytes(), 0644)
	fmt.Printf("Generated %d icons in %s\n", len(icons), outPath)
}

func toPascalCase(s string) string {
	parts := strings.Split(s, "-")
	for i, part := range parts {
		if len(part) > 0 {
			r := []rune(part)
			r[0] = unicode.ToUpper(r[0])
			parts[i] = string(r)
		}
	}
	return strings.Join(parts, "")
}
